site_name: "typeid-python"
site_description: "Python implementation of TypeIDs: type-safe, K-sortable, and globally unique identifiers inspired by Stripe IDs"
site_url: https://akhundmurad.github.io/typeid-python/

theme:
  name: "material"
  features:
    - navigation.instant
  palette:
    - scheme: "default"
      primary: "red"
      accent: "amber"
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: "material/weather-night"
        name: "Switch to dark mode"
    - scheme: "slate"
      primary: "red"
      accent: "amber"
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: "material/weather-sunny"
        name: "Switch to light mode"

repo_name: akhundMurad/typeid-python
repo_url: https://github.com/akhundMurad/typeid-python
edit_uri: "blob/main/docs/"

nav:
  - Introduction: index.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html

plugins:
  - mkdocstrings
  - search:
